sonar.projectKey=finguard-devsecops
sonar.projectName=FinGuard DevSecOps Quality Gate
sonar.sources=finguard,sample_service
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=build/reports/coverage.xml
sonar.python.xunit.reportPath=build/reports/junit.xml
sonar.coverage.exclusions=sample_service/**
